baseURL = "http://brainyard.io/"
languageCode = "en-us"
title = "Brainyard.io"
publishDir = "docs"

theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "A save place for ai and your devs"
  keywords = "frontpage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "Brainyard.io"
    subtitle = "A safe place for your ML-Models"
    keywords = "mlops, models, ai"
    copyright = "brainyard.io"
  # readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "brainyard.io"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
